name: My first workflow
on: push
jobs:
    my_first_job:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v5

        - name: Welcome Message
          run: echo "welcome to my first project"

        - name: list the files
          run: ls
        
        - name: read the file
          run: cat README.md
          
