name: Generate ASCII Art Work
on:
  push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsay
              run: sudo apt-get install cowsay -y
            - name: build cowsay file
              run: cowsay -f dragon "Run for cover i am a dragon" > dragon.txt

            - name: Upload dragon text file
              uses: actions/upload-artifact@v4
              with:
               name: cowsay_file
               path: dragon.txt
               
    test_job:
        runs-on: ubuntu-latest
        needs: build_job
        steps:
            - name: download artifact
              uses: actions/download-artifact@v5
              with:
                    name: dragon.txt
            - name: find the dragon
              run: grep -i "dragon" dragon.txt

            - name: read complete file
              run: cat dragon.txt
    
    deploy_job:
        runs-on: ubuntu-latest
        needs: test_job
        steps:
            - name: download artifact 
              uses: actions/download-artifact@v5
              with:
                    name: dragon.txt 
                        
            - name: read complete file
              run: cat dragon.txt
            

